name: Post Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  notify:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Notify n8n about release branch merged and start documentation workflow
        run: curl -X GET ${{ vars.RELEASE_NOTIFICATION_WEBHOOK }}
