name: Post Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  notify:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Notify n8n about release branch merged and start documentation workflow
        run: curl -X GET https://n8n.currents.dev/webhook/994e4283-4d98-4a68-a0f3-2bcfb251d4e5
